//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QKQStore.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class Categories
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Categories()
        {
            this.Products = new HashSet<Products>();
        }
        [DisplayName("Mã Danh Mục")]
        public int Id { get; set; }
        [DisplayName("Tên Danh Mục")]
        public string Name { get; set; }
        [DisplayName("Ngày Tạo")]
        public Nullable<System.DateTime> CreateAt { get; set; }
        [DisplayName("Ngày Cập Nhật")]
        public Nullable<System.DateTime> UpdateAt { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Products> Products { get; set; }
    }
}
