//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QKQStore.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class Products
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Products()
        {
            this.OrderDetails = new HashSet<OrderDetails>();
            this.ProductImages = new HashSet<ProductImages>();
            Image = "~Content/Pic/Default.jpg";
        }

        [DisplayName("Mã Sản Phẩm")]
        public int Id { get; set; }
        [DisplayName("Danh Mục")]
        public int CategoryID { get; set; }
        [DisplayName("Tiêu Đề")]
        public string Title { get; set; }
        [DisplayName("Giá Tiền")]
        public int Price { get; set; }
        public Nullable<int> TotalPay { get; set; }
        [DisplayName("Giảm Giá")]
        public Nullable<int> Discount { get; set; }
        [DisplayName("Ảnh Sản Phẩm")]
        public string Image { get; set; }
        [DisplayName("Mô Tả")]
        public string Description { get; set; }
        [DisplayName("Ngày Tạo")]
        public Nullable<System.DateTime> CreateAt { get; set; }
        [DisplayName("Ngày Cập Nhật")]
        public Nullable<System.DateTime> UpdateAt { get; set; }
    
        public virtual Categories Categories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderDetails> OrderDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductImages> ProductImages { get; set; }
    }
}
