//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QKQStore.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class Users
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Users()
        {
            this.Orders = new HashSet<Orders>();
        }
        
        [DisplayName("Mã Người Dùng")]
        public int Id { get; set; }
        [DisplayName("Tên Đăng Nhập")]
        [Required(ErrorMessage = "Họ Tên Không Được Để Trống")]
        public string Fullname { get; set; }
    
        [DisplayName("Email")]
        [Required(ErrorMessage = "Email Không Được Để Trống")]
        public string Email { get; set; }

        [DisplayName("Số Điện Thoại")]
        [Required(ErrorMessage = "Số Điện Thoại Không Được Để Trống")]
        public string PhoneNumber { get; set; }
  
        [DisplayName("Địa Chỉ")]
        [Required(ErrorMessage = "Địa Chỉ Không Được Để Trống")]
        public string Address { get; set; }
       
        [DisplayName("Mật Khẩu")]
        [MaxLength(255)]
        [Required(ErrorMessage = "Mật Khẩu Không Được Để Trống")]
        public string Password { get; set; }
        [DisplayName("Vai Trò")]
        public int RoleId { get; set; }
        [DisplayName("Ngày Khởi Tạo")]
        public Nullable<System.DateTime> CreateAt { get; set; }
        [DisplayName("Ngày Cập Nhật")]
        public Nullable<System.DateTime> UpdateAt { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Orders> Orders { get; set; }
        public virtual Roles Roles { get; set; }
    }
}
