//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QKQStore.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class Vouchers
    {
        [DisplayName("Mã Vouchers")]
        public int Id { get; set; }
        [DisplayName("Code")]
        public string Code { get; set; }
        [DisplayName("Phần Trăm Giảm Giá")]
        public Nullable<int> DiscountPercent { get; set; }
        [DisplayName("Đơn Tối Thiểu")]
        public Nullable<int> MinOrderAmount { get; set; }
        [DisplayName("Trạng Thái")]
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> CreateAt { get; set; }
        public Nullable<System.DateTime> UpdateAt { get; set; }
    }
}
